name: Update Library Data

on:
  schedule:
    - cron: '0 0 * * 1'  # Run every Monday at midnight
  workflow_dispatch:      # Allow manual trigger

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Create directories
        run: |
          mkdir -p file
          mkdir -p public

      - name: Download Excel file
        run: |
          curl -L -o "file/library.xls" "${{ secrets.EXCEL_URL }}"

      - name: Transform Excel to JSON
        run: npm run transform

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: Update library data
          title: 'chore: update library data [automated]'
          body: |
            Automated update of library data.
            - Updated books.json from latest Excel file
          branch: update-library-data
          delete-branch: true
